baseURL = "https://u0102655.pages.mech.kuleuven.be/hugo-casadi/"
languageCode = "en-us"
title = "CasADi"
theme = "casadi-theme"

googleAnalytics = ""

pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

publishDir = "public"

[taxonomies]
  tag = ""
  group = ""
  category = ""

[params]
  author = "Joris Gillis, Armin Steinhauser"
  copyright = "Copyright 2018."
  logo = "/_img/logo_2017_horizontal.svg"
  motto = "Build efficient optimal control software, with minimal effort."
  DocsHeader = "Docs v3.3.0"

[blackfriday]
  smartypants = false
  extensions = ["noIntraEmphasis"]
  # extensions = ["hardLineBreak"]
  # extensionsmask = ["autoHeaderIds"]

[menu]
  [[menu.main]]
    url = "/get-casadi/"
    name = "Get CasADi"
    identifier = "get-casadi"
    weight = 2

  [[menu.main]]
    url = "/docs/"
    name = "Docs"
    identifier = "docs"
    weight = 3

  [[menu.main]]
    url = "/about/"
    name = "About"
    identifier = "about"
    weight = 4

  [[menu.main]]
    url = "/support/"
    name = "Support"
    identifier = "support"
    weight = 5

  [[menu.main]]
    url = "/blog/"
    name = "Blog"
    identifier = "blog"
    weight = 6

  # Footer
  # [[menu.footer]]
  #   url = "mailto:me@example.com"
  #   name = "envelope-o"
  #   weight = 1

  [[menu.footer]]
    url = "https://github.com/casadi/casadi"
    name = "github"
    weight = 2

  [[menu.footer]]
    url = "https://twitter.com/casadi_software"
    name = "twitter"
    weight = 3

  [[menu.footer]]
    url = "https://www.youtube.com/channel/UC3VDpv5Pi3R-a2VkcJN1RLw"
    name = "youtube"
    weight = 4

  # [[menu.footer]]
  #   url = "https://github.com/username/"
  #   name = "linkedin"
  #   weight = 4
