baseURL = "https://web.casadi.org/"
languageCode = "en-us"
title = "CasADi"
theme = "casadi-theme"



googleAnalytics = ""

pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

publishDir = "public"

ignorefiles = [ "api" ]
 
[taxonomies]
  tag = ""
  group = ""
  category = ""

[params]
  author = "Joris Gillis, Armin Steinhauser"
  copyright = "Copyright 2023."
  logo = "_img/logo_2017_horizontal.png"
  motto = ""
  casadi_release = "3.5.5"
  casadi_version = "3.5.5"

[blackfriday]
  smartypants = false
  extensions = ["noIntraEmphasis"]
  # extensions = ["hardLineBreak"]
  # extensionsmask = ["autoHeaderIds"]

[markup.goldmark.renderer]
unsafe= true

[menu]

  [[menu.main]]
    url = "/"
    name = "Home"
    identifier = "home"
    weight = 1

  [[menu.main]]
    url = "/get/"
    name = "Try/Install"
    identifier = "get"
    weight = 2

  [[menu.main]]
    url = "/docs/"
    name = "Docs"
    identifier = "docs"
    weight = 3

  [[menu.main]]
    url = "/support/"
    name = "Support"
    identifier = "support"
    weight = 4

  [[menu.main]]
    url = "/source/"
    name = "Source"
    identifier = "source"
    weight = 5

  [[menu.main]]
    url = "/publications/"
    name = "Publications"
    identifier = "publications"
    weight = 6

  [[menu.main]]
    url = "/events/"
    name = "Workshops"
    identifier = "events"
    weight = 7

  [[menu.main]]
    url = "/blog/"
    name = "Blog"
    identifier = "blog"
    weight = 8

  # Footer
  # [[menu.footer]]
  #   url = "mailto:me@example.com"
  #   name = "envelope-o"
  #   weight = 1

  [[menu.footer]]
    url = "https://github.com/casadi/casadi"
    name = "github"
    weight = 2

  [[menu.footer]]
    url = "https://twitter.com/casadi_software"
    name = "twitter"
    weight = 3

  [[menu.footer]]
    url = "https://www.youtube.com/channel/UC3VDpv5Pi3R-a2VkcJN1RLw"
    name = "youtube"
    weight = 4

  # [[menu.footer]]
  #   url = "https://github.com/username/"
  #   name = "linkedin"
  #   weight = 4
